Controllers/CustomerBalanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EarthSkyTime.ViewModels;
using EarthSkyTime.Models;
using EarthSkyTime.BusinessLogic;

namespace EarthSkyTime.Controllers
{
    public class CustomerBalanceController : Controller
    {
        //
        // GET: /CustomerBalance/

        [LogFilterAttribute]
        public ActionResult Index()
        {

            CustomerBalanceBL oCustBalBL = new CustomerBalanceBL();

            ViewBag.FilterValue = "";

            return View(oCustBalBL.GetCustomerBalances());
        }

        [LogFilterAttribute]
        [HttpPost()]
        public ActionResult Index(FormCollection collection)
        {

            ViewBag.FilterValue = collection["filters"].ToString();

            CustomerBalanceBL oCustBalBL = new CustomerBalanceBL();
            return View(oCustBalBL.GetCustomerBalances(collection));
        }

        // Export as csv
        [LogFilterAttribute]
        public void ExportCSV(string filter)
        {
            CustomerBalanceBL oCustBalBL = new CustomerBalanceBL();

            oCustBalBL.ExportDataTableToCsv("AllBalances", filter);
        }
    }
}

Views/CustomerBalance/Index.cshtml
@model IEnumerable< EarthSkyTime.ViewModels.CustomerBalanceVM >
@{
    ViewBag.Title = "Index";
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {

        $("#btnExport").click(function () {
            var url = '@Url.Action("ExportCSV", "CustomerBalance")';
            window.location.href = url + "?filter=" + $("#filters").val();
        });


        function SetFilterValue() {
            if ($("#filterValue").val() != "") {
                $("#filters").val($("#filterValue").val());
            }
        }

        SetFilterValue();
    });
</script>

@RenderPage("~/Views/Shared/_Menu1.cshtml", "All Balances")

<div style="padding:10px">
<h4>Customer Balances</h4>
<input type="hidden" id="filterValue" value="@ViewBag.FilterValue" /> 
<br />

@using (Html.BeginForm("Index", "CustomerBalance", FormMethod.Post, new { name = "form1", id = "form1" }))
{

   
  <div class="form-group">
     <label for="filters">Filters</label>
     <select class="form-control" id="filters" name="filters" >
        <option selected="selected">Date Descending</option>
        <option>Date Ascending</option>
        <option>Balance Ascending</option>
        <option>Balance Descending</option>
        <option>Name Ascending</option>
        <option>Name Descending</option>
    </select>
  </div>
    
       <br />
    
   <input  class="btn btn-primary"  type="submit" value="Reload" />      
    <input type="button"  class="btn btn-primary" value="Export Transactions" id="btnExport" /><br />
   <br />

    <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Balance</th>
        <th>Updated</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      @{
         
    foreach (var o in Model)
    {
         <tr>
            <td>@o.Name</td>
            <td>@String.Format("{0:C}", o.Amount)</td>
            <td>@o.LastTransactionDate</td>
            <td><a href="mailto:@o.Email">@o.Email</a></td>
         </tr>  
    }  
       
    }
    </tbody>
  </table>
    
}
</div>