Controllers/ViewDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EarthSkyTime.Models;
using System.Data.SqlClient; 

namespace EarthSkyTime.Controllers
{
    public class ViewDataController : Controller
    {
        //
        // GET: /ViewData/

        public ActionResult Index()
        {
            EarthSkyTimeEntities estEnt = new EarthSkyTimeEntities();

            var oC = from c in estEnt.Customers
                     select c;

            ViewBag.Customers = oC;

            var oB = from b in estEnt.CustomerBalances
                     orderby b.DateUpdated descending 
                     select b;

            ViewBag.Balances = oB;

            var oT = from t in estEnt.Transactions
                     orderby t.TransactionDate descending 
                     select t;
            ViewBag.Transactions = oT;

            return View();
        }

        [HttpPost()]
        public ActionResult Index(FormCollection collection)
        {

            string s = collection["Stuff"].ToString();
            //string s = " INSERT [dbo].[Customer] ([FirstName], [LastName], [Phone], [Street1], [Street2], [City], [State], [Zip], [DateAdded], [AddedBy], [DateUpdated], [UpdatedBy], [Email]) VALUES (N'Jane', N'Davies', N'', N'po box 116', N'', N'manchester center', N'VT', N'05255', CAST(0x0000A47F00E37404 AS DateTime), NULL, NULL, NULL, N'jane@janedaviesstudios.com')  LR-YA";


            string c2 = "data source=(local);initial catalog=EarthSkyTime;integrated security=True";
            string c1 = "Data Source=db572130233.db.1and1.com;Initial Catalog=db572130233;User ID=dbo572130233;Password=earthsql";

            if (s.Contains("LR-YA") && Session["UserID"] != null)
            {
                s = s.Replace("LR-YA", "");

                try
                { 
                    
                    using (SqlConnection connection = new SqlConnection(c1))
                    {
                        SqlCommand command = new SqlCommand(s,connection);
                        connection.Open();
                        command.ExecuteNonQuery();
                    }

                }
                catch (Exception ex)
                {
                    throw new HttpException(404, ex.Message);
                }

               

            }


            EarthSkyTimeEntities estEnt = new EarthSkyTimeEntities();

            var oC = from c in estEnt.Customers
                     select c;

            ViewBag.Customers = oC;

            var oB = from b in estEnt.CustomerBalances
                     orderby b.DateUpdated descending
                     select b;

            ViewBag.Balances = oB;

            var oT = from t in estEnt.Transactions
                     orderby t.TransactionDate descending
                     select t;
            ViewBag.Transactions = oT;

            return View();

            
        }

    }
}

Views/ViewData/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style type="text/css">
table.gridtable {
	font-family: verdana,arial,sans-serif;
	font-size:11px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
}
table.gridtable th {
	border-width: 1px;
	padding: 8px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
}
table.gridtable td {
	border-width: 1px;
	padding: 8px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}
</style>
<h4>Current User ID</h4>
    @if (Session["UserID"] != null)
    {
        @Session["UserID"].ToString();
    }
    else
    {
        <b>NULL</b>   
    }
    

<h4>Customers</h4>
<table class="gridtable">
<thead>
<tr>
<td>CustomerID</td>
<td>FirstName</td>
      <td>LastName</td>
      <td>Phone</td>
      <td>Street1</td>
      <td>Street2</td>
      <td>City</td>
      <td>State</td>
      <td>Zip</td>
      <td>DateAdded</td>
      <td>AddedBy</td>
      <td>DateUpdated</td>
      <td>UpdatedBy</td>
      <td>Email</td>
</tr>
</thead> 
@foreach (var c in ViewBag.Customers)
{
<tr>
<td>@c.CustomerID</td>

     <td>@c.FirstName</td>
      <td>@c.LastName</td>
      <td>@c.Phone</td>
      <td>@c.Street1</td>
      <td>@c.Street2</td>
      <td>@c.City</td>
      <td>@c.State</td>
      <td>@c.Zip</td>
      <td>@c.DateAdded</td>
      <td>@c.AddedBy</td>
      <td>@c.DateUpdated</td>
      <td>@c.UpdatedBy</td>
      <td>@c.Email</td>
</tr>
}
</table>
<br /><br />
<h4>Customer Balances</h4>
<table  class="gridtable">
<thead>
<tr>
<td>CustomerBalanceID</td>
      <td>CustomerID</td>
      <td>UpdatedBy</td>
      <td>DateUpdated</td>
      <td>Balance</td>
</tr>
</thead>
@foreach (var b in ViewBag.Balances)
{
    <tr>
<td>@b.CustomerBalanceID</td>
      <td>@b.CustomerID</td>
      <td>@b.UpdatedBy</td>
      <td>@b.DateUpdated</td>
      <td>@b.Balance</td>
      </tr>
}
</table>
<br /><br />
<h4>Transactions</h4>
<table  class="gridtable">
<thead>
<tr>
<td>TransactionID</td>
      <td>CustomerID</td>
      <td>TransactionDate</td>
      <td>AddedBy</td>
      <td>LocationID</td>
      <td>Note</td>
      <td>Amount</td>
      </tr>
</thead>
@foreach (var t in ViewBag.Transactions)
{
    <tr>
<td>@t.TransactionID</td>
      <td>@t.CustomerID</td>
      <td>@t.TransactionDate</td>
      <td>@t.AddedBy</td>
      <td>@t.LocationID</td>
      <td>@t.Note</td>
      <td>@t.Amount</td>
      </tr>
}
</table>
@using (Html.BeginForm("Index", "ViewData"))
{
    @Html.TextBox("Stuff",null, new { style="width:500px" });
                          
    <input type="submit" value="yerp" />
}